import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

/**
 * Prisma 7.10 merges every `.prisma` file in the schema folder natively
 * (confirmed by spike, Phase 3a). Each vertical module keeps its own schema
 * fragment under its own package (e.g.
 * packages/verticals/dealership/prisma/schema.prisma) so the module owns its
 * tables without packages/database ever importing a concrete module — this
 * script copies each fragment into packages/database/prisma/<slug>.prisma
 * before generate/migrate, purely by walking the filesystem (never a package
 * import), so there is no dependency-graph cycle.
 *
 * Copies are marked with a header comment and overwritten every run — never
 * hand-edit packages/database/prisma/<slug>.prisma; edit the module's own
 * fragment instead.
 */
const HEADER = '// GENERATED — copied from the vertical module\'s own prisma/schema.prisma by\n// sync-vertical-schemas.ts. Do not edit this file; edit the source instead.\n\n';

function main() {
  const databasePrismaDir = join(import.meta.dirname, '..', 'prisma');
  const verticalsDir = join(import.meta.dirname, '..', '..', 'verticals');
  if (!existsSync(verticalsDir)) return;

  for (const slug of readdirSync(verticalsDir, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name)) {
    const source = join(verticalsDir, slug, 'prisma', 'schema.prisma');
    if (!existsSync(source)) continue;
    const dest = join(databasePrismaDir, `${slug}.prisma`);
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, HEADER + readFileSync(source, 'utf8'));
    console.log(`synced ${slug}.prisma from ${source}`);
  }
}

main();
